import { GradientBG } from '@/components/GradientCanvas';
import ClientToaster from '@/components/Toaster';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Noto_Sans, Noto_Sans_KR } from 'next/font/google';

const NotoSansKR = Noto_Sans_KR({ subsets: ['latin'], weight: ['400', '600'] });
const NotoSans = Noto_Sans({ subsets: ['latin'], weight: ['400', '600'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSansKR.className} ${NotoSans.className}`}>
        <GradientBG />
        <div className="hide-scrollbar relative z-10 h-screen w-screen overflow-y-scroll text-white">
          {children}
        </div>
        <ClientToaster />
      </body>
    </html>
  );
}
